### ISSUE TITLE
1 Arduino only

### ISSUE THREAD

**Issue by Rey1635** [cole8888/SRNE-Solar-Charge-Controller-Monitor#10]
As a newbie, I would like to ask how to use only 1 arduino to read the battery voltage and the charging state status of the SRNE? How will I connect it to arduino? Thank you very much for your help.

**Comment by cole8888** [comment]
Hi, sorry about not thinking about that, I'll make a schematic / code for a single arduino and charge controller.
Will you have access to an esp8266? I'm thinking i can get it to work with just one esp8266. That way you don't have to deal with the RF24 stuff.

**Comment by Rey1635** [comment]
Thank you very much for your response.. I do have an esp8266. I'll just wait for your update.  God Bless You always.

**Comment by cole8888** [comment]
You are also going to need a MAX3232 breakout board since the voltage level the charge controller uses to talk over rs232 isn't compatible with the Arduino and needs to be converted.

I found [this](https://www.amazon.com/Treedix-MAX3232-Convert-Transceiver-Breakout/dp/B09BCKWL8V) on amazon and it should work.

I'm not sure where you are from but try searching for "MAX3232 breakout" and see if you can find something simmilar to that, feel free to send links to the ones you find and I can try to tell you if they will work.

If you can only find ones which look like [this](https://www.amazon.com/NOYITO-Module-Conversion-Arduino-communicates/dp/B07BJJC3R6/) that's ok, you'll need to find a way to connect to the DB9 connector using something like [this](https://www.amazon.com/Connector-Female-Adapter-Terminal-Signal/dp/B086VYDPKH/).

Also the charge controller uses a RJ12 (6P6C) jack for the modbus connector so you are going to need a cable like [this](https://www.amazon.com/Pack-Feet-Cable-Modular-Black/dp/B01M0G7VP4/) which you will need to splice in half and strip the wires. This may look like a phone cable or Ethernet cable, but it isn't, it has 6 contacts.

**Comment by cole8888** [comment]
I managed to get a ESP8266 to talk to the charge controller, will upload code, schematic and pictures shortly.

**Comment by Rey1635** [comment]
I do have one of [this](https://www.amazon.com/HiLetgo-Level-Converter-Board-Rs232/dp/B00LUDCAXQ/ref=sr_1_2?crid=2SUUNSQ4SYUPG&keywords=Mini+RS232+to+TTL+chip+MAX3232&qid=1668986257&sprefix=mini+rs232+to+ttl+chip+max3232%2Caps%2C283&sr=8-2) and I already have a RJ12 (6P6C).  Thank you very much

**Comment by cole8888** [comment]
Nice, that should work!

I uploaded some examples and much more detailed instructions, have a look at them [here](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/tree/main/Arduino-Version).

Also [this particular example](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/blob/main/Arduino-Version/Single-Charge-Controller/SOLAR_SINGLE_CC/SOLAR_SINGLE_CC.ino) is the one you are interested in, just make sure you replace the `MAX3232_RX` and `MAX3232_TX` values to whatever pins you are using. (Most of that file is spent writing the data to the serial monitor so it isn't as scary as it looks at first.)

Let me know if you run into any problems :)

**Comment by Rey1635** [comment]
Thank you very much.  I'm so excited to start my project.  May God Bless You always.

**Comment by Rey1635** [comment]
I tried to the upload code on my esp8266 but there is an error ("'class Modbus' has no member named 'start'") on master.start(); I've already  installed the modbus-esp8266 library.

**Comment by cole8888** [comment]
I'm not using that modbus library, I used https://github.com/smarmengol/Modbus-Master-Slave-for-Arduino
There are instructions in that repoitory for how to install it, I don't think it is in the Arduino IDE.

**Comment by Rey1635** [comment]
thanks for the link of the library.. error has been solved.

**Comment by Rey1635** [comment]
Sad to say no luck for me.. I have already tried with arduino. 
![Untitled](https://user-images.githubusercontent.com/118655087/202995085-5c1fbaff-086a-4a71-ba37-c5e92bc8c771.png)

**Comment by Rey1635** [comment]
Maybe I should purchase a different type of  MAX3232 breakout board.

**Comment by cole8888** [comment]
How do you have it wired up? You may have RX and TX backwards on either the arduino side or the charge controller side.
Please send a picture of the wiring you are using.

**Comment by Rey1635** [comment]
Here is how  I wired up.
![Untitled](https://user-images.githubusercontent.com/118655087/203237291-dbe52dd2-9709-4b2e-8a63-920ae8181957.png)

**Comment by cole8888** [comment]
On the arduino side the you have the VCC and GND reversed. Also I'm not sure what roles you have assigned to D2 and D3. For getting it started for the first time, can you stick to D1 and D2 since those are the only pins I tested.
![image](https://user-images.githubusercontent.com/32819560/203245493-741381ff-6b8b-442d-bc40-88d784bf02fc.png)
Your RX and TX lines seem correct though.

**Comment by cole8888** [comment]
I'm pretty sure D3 cannot be used for software serial according to some stuff I found online. Just use D1 and D2 for now since I know those work.

**Comment by Rey1635** [comment]
Thank you very much.

**Comment by Rey1635** [comment]
btw, can I apply this on arduino uno? What pins should I use? Thank you

**Comment by cole8888** [comment]
Were you able to get it to work?

I have Arduino nano wiring examples [here](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/tree/main/Arduino-Version/Single-Charge-Controller/Photos%20and%20Schematics).
So, if you follow those examples use:
`#define MAX3232_RX 2`
`#define MAX3232_TX 3`

**Comment by Rey1635** [comment]
still no luck.  I will  just purchase other type of MAX3232 breakout.

**Comment by cole8888** [comment]
Darn.

Here is the one I use by the way: https://www.digikey.com/en/products/detail/mikroelektronika/MIKROE-602/4495610

**Comment by cole8888** [comment]
Also which charge controller are you using?

**Comment by Rey1635** [comment]
I'm using SRNE ML2420

**Comment by cole8888** [comment]
Yeah that should work, appears to be nearly identical to the ML2440 which is one of the ones I use and the manual says it supports modbus and the bluetooth module which means we should be able to talk to it since the bluetooth module is pretty much doing the same thing. 

If you do get one of the ones with the DB9 connector (like the one I used) make sure you get a DB9 breakout adapter like [this](https://www.amazon.com/Connector-Adapter-Terminal-Signal-Module/dp/B071DS5GTW).

**Comment by Rey1635** [comment]
ok. thanks for the suggestion, I'll do get that one.

**Comment by Shadow-Genesis** [comment]
I know I maybe a little late on saying this. But to the serial board, I just found a USB cable for it. It is USB-A to RS232 Serial 6P6C on Amazon. I use a Raspberry PI for mine so USB works for me, and my work for others.

[https://www.amazon.com/dp/B07JGRJR4V?psc=1&ref=ppx_yo2ov_dt_b_product_details](url)

**Comment by Rey1635** [comment]
Good day, I would like to ask if my connections are correct.
![try](https://user-images.githubusercontent.com/118655087/204792605-950e4af8-6e9c-462c-abb8-7c00d7b9d247.png)
 and I changed the arduino code with this..
![try2](https://user-images.githubusercontent.com/118655087/204792783-0ae32221-c986-4d6b-8a11-987b0a182c5f.png)

 Thank you very much

**Comment by cole8888** [comment]
Your connections are correct, but for the code you need to have a D in front of the number, so use D1 and D2.

The colour of the wires you chose going from the 6P6C jack to the DB9 connector in your diagram aren't the actual colours right? 1 should be white, 2 should be black and 3 should be red. Maybe just compare your connector with mine to make sure our connectors are the same:
![image](https://user-images.githubusercontent.com/32819560/204797135-05df63c4-670a-4f51-bebf-e48cbfb5c562.png)

**Comment by Rey1635** [comment]
Here's mine..
![www](https://user-images.githubusercontent.com/118655087/204799285-37201944-5fd9-4b9f-9744-9398f69b10b9.png)

**Comment by Rey1635** [comment]
Here's mine..
![www](https://user-images.githubusercontent.com/118655087/204799285-37201944-5fd9-4b9f-9744-9398f69b10b9.png)

**Comment by Rey1635** [comment]
changed the code
#define MAX3232_RX D1 // RX pin. If following my ESP8266 instructions use D1.
#define MAX3232_TX D2 // TX pin. If following my ESP8266 instructions use D2.

but  there is an error:
'D1' was not declared in this scope

**Comment by cole8888** [comment]
Interesting, seems like some ESP8266 do not support the D labels. Lets just use the pin numbers directly.
```
#define MAX3232_RX 5 // RX pin. If following my ESP8266 instructions use D1.
#define MAX3232_TX 4 // TX pin. If following my ESP8266 instructions use D2.
```

**Comment by cole8888** [comment]
Here is your diagram with the colors from your cable.
![204792605-950e4af8-6e9c-462c-abb8-7c00d7b9d247](https://user-images.githubusercontent.com/32819560/204811766-5f9aae0c-f29a-4961-8306-2ca99cc88520.png)

**Comment by Rey1635** [comment]
Still no luck even with new arduino nano...  I followed your given pictures..
#define MAX3232_RX 2 
#define MAX3232_TX 3

**Comment by cole8888** [comment]
How are you going from the RJ12/6P6C cable to the DB9 connector? 

I know that when building mine I had some trouble making good contact at first. Could you check with a multimeter to see if you are getting continuity on those three lines by putting one end on the RJ12 contact and the other on the corresponding solder connection of the DB9 connector on the underside of the MAX3232 connector board?

Also I know sometimes I've had to reboot some of my charge controllers after they stop reporting data, but it's quite rare. Try disconnecting one cable from both the battery and the solar panels and leaving it for like 10 seconds then plugging it back in.

Also check all your other connections to see if they are loose or have intermittent contact. In my experience DuPont connectors are loose alot so investigate those especially.

Also do you have a link to the exact MAX3232 board you bought, I'm curious if the pinout might be different for some reason.

**Comment by Rey1635** [comment]
I use this one https://www.amazon.com/Anmbest-Solderless-Terminal-Connector-Breakout/dp/B07S7M24C3 and here is my MAX3232 board  https://www.elecrow.com/rs232-to-ttl-converter-module-max3232-p-762.html..

**Comment by cole8888** [comment]
The MAX3232 board has the same pinout as mine and the breakout should eliminate contact issues.

For the ground (Green on RJ12) are you using the GND terminal block on the breakout connector? If so can you switch to using pin 5 instead? It looks like some of these breakouts don't actually connect that terminal to pin 5.

Also just to clarify BLUE->3, YELLOW->2, GREEN->5

**Comment by Rey1635** [comment]
I'm using pin 5 as ground on  breakout connector. also blue to pin 3, yellow to pin 2 and green to 5.  I will try reboot my charge controller

**Comment by Rey1635** [comment]
Error when trying to communicate with the charge controller.  Here is my connections
![IMG_20221206_112753_714](https://user-images.githubusercontent.com/118655087/205806576-6a88b770-e4e7-4976-a124-566dd916f938.jpg)


![IMG_20221206_113757_887](https://user-images.githubusercontent.com/118655087/205807235-a70b6bb3-a92e-4ecd-a5a4-bc95bc426065.jpg)

RJ12 CONNECTIONS
RJ12 pin 1 to db9 pin 3
RJ12 pin 2 to db9 pin 2
RJ12 pin 3 to db9 pin 5

- charge controller rebooted
- all wire connections checked using multimer
- Charge controller Rj12 pin has been tested using renogy Bluetooth module to check if the RJ12 pin of functioning properly

**Comment by cole8888** [comment]
Your connections look good. Let's try changing the ESP8266 pins, maybe those pins are reserved on your variant?

Move your Blue one (D1) over to D5 and Purple one (D2) over to D6 and then change the code to
```
#define MAX3232_RX 14
#define MAX3232_TX 12
```

**Comment by cole8888** [comment]
As a sanity check I just went and did a fresh clone of the repo, changed only those two lines and using this configuration I was able to get data from my ML2440.
So I'm not really sure what's going on here. My money is on the MAX3232 not working correctly since the capacitors on that thing look way smaller than the ones on mine.

![PXL_20221206_040444458~2](https://user-images.githubusercontent.com/32819560/205811267-780858dc-ffa2-4323-91ae-23b18c3a151d.jpg)

**Comment by Rey1635** [comment]
Thank you.. I will replace my MAX3232 module

**Comment by cole8888** [comment]
Hold on! I think I thought your connector was upside down, can you send another picture of your RJ12 jack?

**Comment by cole8888** [comment]
One with the full connector please so I can see the wire colors through the clear plastic and see which way the wire exits the connector.

**Comment by cole8888** [comment]
Like this:
![image](https://user-images.githubusercontent.com/32819560/205814946-972a4a74-435e-4087-bea7-f33a87e64244.png)

**Comment by Rey1635** [comment]
![conn](https://user-images.githubusercontent.com/118655087/205817203-6cd85716-b60f-4052-b6f8-5d8309109a15.png)

**Comment by cole8888** [comment]
Yeah it's the way I thought it was, darn. I'm going to try the wiring diagram the renogy guides use where RX and TX are flipped relative to what I'm doing.
![image](https://user-images.githubusercontent.com/32819560/205818022-0fce9e3a-cef4-4ea0-aaae-98171a1e3919.png)

**Comment by cole8888** [comment]
That didn't work, even if I flipped the ones on the ESP8266 side. Seems like the way I have it is the only way it works. I wonder if the renogy ones use a different pinout.

**Comment by Rey1635** [comment]
I will try this 
#define MAX3232_RX 14
#define MAX3232_TX 12

**Comment by cole8888** [comment]
Good luck, I'm really sorry this is giving you so much trouble.

**Comment by Rey1635** [comment]
Thats always part of learning.

**Comment by Rey1635** [comment]
Good day, I've successfully read values from my charge controller and an ESP32 but using this code...
#define RXD2 16
#define TXD2 17

int num_data_registers = 30;
int num_info_registers = 17;

#include <ModbusMaster.h>
ModbusMaster node;


void setup()
{
  Serial.begin(115200);
  Serial.println("Started!");

  // create a second serial interface for modbus
  Serial2.begin(9600, SERIAL_8N1, RXD2, TXD2); // is SERIAL_8N1 correct?

  int modbus_address = 255; // my Renogy Wanderer has an (slave) address of 255! Not in docs???
  node.begin(modbus_address, Serial2); 
}


void loop()
{
  static uint32_t i;
  uint8_t j, result;
  uint16_t data_registers[num_data_registers];
  uint16_t info_registers[num_info_registers];
  
  i++;
  
  // set word 0 of TX buffer to least-significant word of counter (bits 15..0)
  node.setTransmitBuffer(0, lowWord(i));  
  // set word 1 of TX buffer to most-significant word of counter (bits 31..16)
  node.setTransmitBuffer(1, highWord(i));
 
  // Read the 30 data registers
  result = node.readHoldingRegisters(0x100, num_data_registers);
  if (result == node.ku8MBSuccess)
  {
    Serial.println("Successfully read the data registers!");
    for (j = 0; j < num_data_registers; j++)
    {
      data_registers[j] = node.getResponseBuffer(j);
      Serial.println(data_registers[j]);
    }
    Serial.println("---");
  }
  else {
    Serial.print("Failed to read the data registers... ");
    Serial.println(result, HEX); // E2 is timeout
  }

  // Read the 17 info registers
  result = node.readHoldingRegisters(0x00A, num_info_registers);
  if (result == node.ku8MBSuccess)
  {
    Serial.println("Successfully read the info registers!");
    for (j = 0; j < num_info_registers; j++)
    {
      info_registers[j] = node.getResponseBuffer(j);
      Serial.println(info_registers[j]);
    }
    Serial.println("---");
    Serial.println();
  }
  else {
    Serial.print("Failed to read the info registers... ");
    Serial.println(result, HEX); // E2 is timeout
  }
  delay(1000);
}

Can I ask your help how to modify this code to read only the battery voltage and the charging state status? Thank you & God Bless

**Comment by cole8888** [comment]
Awesome!
This is very interesting, can you tell me what modbus library you are using, also can you send a copy of the data you are receiving from the charge controller?
I do not have an ESP32 on hand so I won't be able to test it.
The modbus slave address is different than it is for all of my charge controllers, which is interesting. This could explain why you were not able to talk to it with my code.

**Comment by cole8888** [comment]
Also if you could send a picture of the charge controller display so I know which charging mode and voltage it has at the moment that would be helpful.

**Comment by Rey1635** [comment]
Library used is https://github.com/syvic/ModbusMaster.
Here is my serial output..
![qq](https://user-images.githubusercontent.com/118655087/206363147-3a095f6e-f919-4f20-aca8-a622d5a8219e.png)
and the charge controller display..
![IMG_20221208_130952_838](https://user-images.githubusercontent.com/118655087/206363221-fbd43d54-3a97-4aea-bb2d-1ea313e92d31.jpg)

**Comment by Rey1635** [comment]
I found the code from here https://forum.arduino.cc/t/trying-to-read-registers-from-a-solar-charge-controller-over-rs232-solved/1039864/11

**Comment by cole8888** [comment]
Hey can you include the data registers too? That's where the information you want is.

**Comment by Rey1635** [comment]
Sorry, cant understand what data register is, I just copied the code from here https://forum.arduino.cc/t/trying-to-read-registers-from-a-solar-charge-controller-over-rs232-solved/1039864/11 and upload it to esp32

**Comment by cole8888** [comment]
In the console output that script prints out two sets of data, one of them is called info registers and one is data registers. The data registers are the ones we want. There should be a header with the text "Successfully read the data registers!" printed above them.
Also could you send a picture of how you wired up the the ESP32? I'm trying to see if changing the modbus address will make my code work.

**Comment by Rey1635** [comment]
console output for first set..
![hhh](https://user-images.githubusercontent.com/118655087/206367007-69054478-e47a-4652-ae45-fdf7316cb3bc.png)

I just followed this..
![6af2468ee0561ca003c88879786ce155a797a8ea](https://user-images.githubusercontent.com/118655087/206367147-1393e835-5531-420e-9cb4-801d4fc2fae0.jpeg)

**Comment by cole8888** [comment]
Their TX and RX in the diagram seem to be opposite to mine so I just wanted to see how you physically hooked it up so I could assign the correct pin numbers in my code for you to try out.

**Comment by cole8888** [comment]
An updated picture like this would be awesome: https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/issues/10#issuecomment-1338694262

**Comment by Rey1635** [comment]
![IMG_20221208_135338_276](https://user-images.githubusercontent.com/118655087/206369250-3a8fe92f-a7b4-44c2-b317-d198667a8ac1.jpg)

**Comment by cole8888** [comment]
This data seems to be in the exact same format as what my program is expecting.

In the program we were working with previously can you try these settings?
```
#define MAX3232_RX 17
#define MAX3232_TX 16
```
and 
`
#define MODBUS_SLAVE_ADDR 255
`
(got it backwards, see later message)

**Comment by Rey1635** [comment]
![IMG_20221208_135338_276](https://user-images.githubusercontent.com/118655087/206370530-64b21dd5-51c5-4023-984b-3c94d2c223f6.jpg)

**Comment by cole8888** [comment]
Shoot I got it backwards :stuck_out_tongue:, try:
```
#define MAX3232_RX 16
#define MAX3232_TX 17
```
instead please.

**Comment by Rey1635** [comment]
using an esp32 there is an error SoftwareSerial.h: No such file or directory

**Comment by cole8888** [comment]
damnit, looks like that's going to be a problem, lets not use the ESP32 for now.

Could you pull out your ESP8266 and wire it up like we had it [before](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/issues/10#issuecomment-1338694262)?
D1 -> MAX3232 RX pin
D2 -> MAX3232 TX pin
VCC and ground like before.

Then use
```
#define MAX3232_RX 5
#define MAX3232_TX 4
```
Also make sure to change this line:
`#define MODBUS_SLAVE_ADDR 255`

**Comment by Rey1635** [comment]
![222](https://user-images.githubusercontent.com/118655087/206376539-af952a0d-c23a-4687-8ee9-ba8b4f51c53b.png)
![aaaa](https://user-images.githubusercontent.com/118655087/206376569-a9b64d9e-7ff0-41d6-941e-271bb5a9891f.jpg)

**Comment by cole8888** [comment]
Damnit, I'll jerry rig something quick which should let you access the information on your ESP32, just give me a minute.

**Comment by cole8888** [comment]
WAIT, you have D1 and D2 cables backwards!

**Comment by cole8888** [comment]
Green should be D1, purple D2

**Comment by Rey1635** [comment]
green to D!, purple to D2 is still no luck.. and with this connection the COM icon in charge controller does not appear but if purple to D1 and green to D2 the COM icon in charge controller appears but still no luck..

**Comment by cole8888** [comment]
That is bizarre. If the COM icon appears it is making a connection though.
It's too late for me to keep going but let me know if this displays the stuff you want. Tomorrow I can try and get the rest of the information out of it.
I couldn't compile this because I don't know what ESP32 you are using and I kept getting library issues so let me know if there is a problem.
[solar.zip](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/files/10183033/solar.zip)

**Comment by Rey1635** [comment]
ok.. Thank you

**Comment by Rey1635** [comment]
ok.. Thank you

**Comment by cole8888** [comment]
I've dug into it a bit more and I'm pretty sure I found what is causing the problem.

The reason address 255 is working for you on that one program is because that is a special address which all controllers will respond to regardless of what their actual address is. For some reason your charge controller has an address that is not 1 unlike every other controller I've seen so far.
The library in that example you provided accepts address 255 and I am able to get my controllers to respond, but using the modbus library I chose for my program it seems to not accept address 255.

I dug into the source code of the library and sure enough: 
![image](https://user-images.githubusercontent.com/32819560/206619385-c340eb07-7897-4866-9a43-6654279cae7b.png)
![image](https://user-images.githubusercontent.com/32819560/206619495-d6839af4-b796-46eb-a575-aca30d9a14d0.png)
By manually changing both of those from 247 to 255 and restarting the Arduino IDE then re-uploading to the esp8266 I was able to get address 255 working on my program.

If you don't mind, in your Arduino libraries folder can you swap the library source code file (Modbus-Master-Slave-for-Arduino -> ModbusRtu.h) with this one https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/blob/test-address-fix/Arduino-Version/Single-Charge-Controller/ModbusRtu.h, then wire up your esp8266 and program it with this:
https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/blob/test-address-fix/Arduino-Version/Single-Charge-Controller/SOLAR_SINGLE_CC/SOLAR_SINGLE_CC.ino (I indicated which connections to make in the comments).

**Comment by Rey1635** [comment]
Thank you very much! I've already got it!   God Bless & Merry Christmas!

**Comment by Luisdjnas** [comment]
Hello, I have a srne 2420 and I have messed up the internal software by mistake with an app. Could someone tell me how to put the original software back??
