### ISSUE TITLE
Software srne ml2420

### ISSUE THREAD

**Issue by Luisdjnas** [cole8888/SRNE-Solar-Charge-Controller-Monitor#13]
Hello, I tried to update the ml2420 through an app and the installation failed. Is there any way to enter the original software?

**Comment by cole8888** [comment]
I'm not sure. Assuming you could get the equipment to talk to the controller, there is a command in the modbus manual for resetting the controller to factory defaults. I don't know if this will be able to fix a failed firmware update though.

I also found a manual of a different SRNE charge controller which said you could press the "select" button (rightmost button for this one maybe) for 20 seconds to reset it, I don't know if it will work with your controller though.

Does it turn on at all or does it show anything on the screen/led indicators?

If it is still under warranty you are probably better off trying to go through whoever you bought it from to get a replacement. If not then it might be best to just get a new controller.

**Comment by Luisdjnas** [comment]
I've tried holding the button down and it doesn't work.  Unfortunately the seller does not cover a guarantee of what happened.  From the app it does not let you restore it to factory settings either.  The controller shows nothing on the screen but the bt-01 module turns on.  I don't know what I could do anymore.

**Comment by Luisdjnas** [comment]
there is no way to enter the original software again?? I would be very grateful for a solution.

**Comment by Luisdjnas** [comment]
there is no way to enter the original software again?? I would be very grateful for a solution.

**Comment by cole8888** [comment]
I don't work for SRNE, I don't know.

You'll have to contact SRNE support to see if there is anything you can do / see if they will replace it.

**Comment by Luisdjnas** [comment]
I got in touch and they didn't give me any solution, I just had to buy another one. that was the problem. 😔

**Comment by Luisdjnas** [comment]
I got in touch and they didn't give me any solution, I just had to buy another one. that was the problem. 😔
