### ISSUE TITLE
Can't read data, help please.

### ISSUE THREAD

**Issue by Shadow-Genesis** [cole8888/SRNE-Solar-Charge-Controller-Monitor#17]
Hello I'm trying to use the python script for the raspberry pi again, used it last year it worked great. When I go to read any data from my ML2420 I get errors. I connect over a USB serial cable and I have the bluetooth adapter and it works fine.......

My code, the same other then a debug line I added.
`def run():
    if False: #I added this if as a DEBUG
        response = modbus.read_holding_registers(26, 1, unit=0)
        print(response)
    while True:
        try:
            # Read 35 registers from the controller starting at address 0x0100 (Decimal 256) until 0x0122 (Decimal 290)
            response = modbus.read_holding_registers(256, 35, unit=0)
            if(JSON_OR_TEXT == "TEXT"):
                printDataText(response)
            else:
                print(convertToJson(response, False))
            time.sleep(DELAY_BETWEEN_REQUESTS)
        except Exception as e:
            if(JSON_OR_TEXT == "TEXT"):
                print("Failed to read data, reconnecting...", e)
            else:
                print(convertToJson(None, True))
            reconnectModbus()
            time.sleep(DELAY_BETWEEN_REQUESTS)`

I get the error "Failed to read data, reconnecting... 'ModbusIOException' object has no attribute 'registers' "
And when I do my debug I get "Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 4 bytes (0 received)"

I really could use the help right now.

**Comment by cole8888** [comment]
Hi, sorry for the delayed response. I've been able to reproduce the problem on my PI also and I'll try to have a fix for it soon.

**Comment by Shadow-Genesis** [comment]
Thank you, and wow that was fast.

**Comment by cole8888** [comment]
The correct setup is Raspberry pi GPIO14 goes to MAX3232 TX and GPIO15 goes to RX

While trying to reproduce it I had the wires backwards and got the behavior you mentioned. After flipping them to be correct I was able to read data. Also what python/pymodbus version are you using?

**Comment by cole8888** [comment]
I just double checked the wiring photos in that directory and they are correct.

This one is probably the easiest to compare against:
https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/blob/main/RaspberryPi-Examples/RaspberryPi-Top-View.jpg

**Comment by Shadow-Genesis** [comment]
I'm using a USB connecter, and I did check and redo my wires. Pin 1 to my RX and pin 2 to my TX and pins 3 & 4 to ground. Pins 5 & 6 are power and not connected.

I just tried flipping the tx and rx to make sure and still the same.

FYI: Pins 5 & 6 give off battery voltage.

**Comment by Shadow-Genesis** [comment]
So I got a bit of an update. I have for my pc the Solar Station Monitor software. With it I can connect if I set the device ID to 255. Still not working with the python script. Any ideas?

**Comment by cole8888** [comment]
Address 255 is a special address that all charge controllers respond to no matter what their current address is.

Your controller must have a different address than mine. Ran into a similar thing with the Arduino versions and I fixed it there by forcing address 255, but I didn't realize the python version would also have this problem.

Try replacing the line with `read_holding_registers` with this:
`response = modbus.read_holding_registers(256, 35, unit=1, slave=255)`

**Comment by Shadow-Genesis** [comment]
So adding the "slave" parameters fixed it. I would like to note that the code works without the "unit" parameters and that the "slave" needs to be your device ID.  

`response = modbus.read_holding_registers(256, 35, slave=1)`

Thank you for your help, hope this helps others.

**Comment by cole8888** [comment]
@Shadow-Genesis Just wondering, did this work when you set slave to 255 instead of 1? If it worked with 255 I'll update the program since it should work for all controllers.

**Comment by Shadow-Genesis** [comment]
Both. My device is ID 1. And from what I read in the PDF that talks about how data is sent and received, 255 is a device ID that all respond to. Mostly for use with bluetooth adapters and remote displays. So in short from what I read, the device ID 255 is a plug and play ID

**Comment by cole8888** [comment]
Ok, I'll update the script to use 255, should prevent issues in the future. Thanks!

**Comment by Shadow-Genesis** [comment]
I had been making since last night a python class that would handle the SRNE data, makes it cleaner for me. I just got a bit of code I think you may want to add.

`
deviceID=None
response = self.modbus.read_holding_registers(26, 1, slave=255)
deviceID = response.registers[0]
response = self.modbus.read_holding_registers(256, 35, slave=deviceID)
`

its just a little auto device ID. I do not think it would work with more then one slave connected, but for one it should be fine
