### ISSUE TITLE
MobusIOException object has no attribute 'registers'

### ISSUE THREAD

**Issue by magorm** [cole8888/SRNE-Solar-Charge-Controller-Monitor#18]
Getting the error 'has no attribute registers' when running SolarMonitor.py. Need your help :-)

**Comment by cole8888** [comment]
What charge controller are you using and how have you connected to it?

Can you try replacing the line containing `read_holding_registers` with `response = modbus.read_holding_registers(256, 35, unit=1, slave=255)`.

If your charge controller address is different than mine this will fix it.

**Comment by magorm** [comment]
Thanks so much. May I know the version of pymodbus you're using?
Here is how I connected SNRE SCC to my Laptop running the Python script:
![x drawio](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/a56ba2b7-4a11-4f0e-a1c4-8f8c8f96e296)

**Comment by magorm** [comment]
> What charge controller are you using and how have you connected to it?
> 
> Can you try replacing the line containing `read_holding_registers` with `response = modbus.read_holding_registers(256, 35, unit=1, slave=255)`.
> 
> If your charge controller address is different than mine this will fix it.

Did not work. I think the issue is related to USB adapter?

**Comment by cole8888** [comment]
Which USB adapter are you using? It might not use the right voltage.

**Comment by cole8888** [comment]
Also, can you show how you wired the serial adapter up to the RJ12 cable?

**Comment by magorm** [comment]
> Which USB adapter are you using? It might not use the right voltage.

I am using this adapter: USB to TTL converter UART module CH340G CH340 3.3V 5V switch

**Comment by magorm** [comment]
> Also, can you show how you wired the serial adapter up to the RJ12 cable?

![Uploading solar-monitor.png…]()

**Comment by cole8888** [comment]
The CH340G won't work, it only does +/-5V where RS232 needs +/-13V.

You'll need to use a usb to RS232 converter like this one:
https://www.amazon.ca/StarTech-com-USB-Serial-Adapter-Prolific/dp/B00GRP8EZU

Also, I can't see that image so I'm not sure how you wired it up to your charge controller.

**Comment by magorm** [comment]
> The CH340G won't work, it only does +/-5V where RS232 needs +/-13V.
> 
> You'll need to use a usb to RS232 converter like this one: https://www.amazon.ca/StarTech-com-USB-Serial-Adapter-Prolific/dp/B00GRP8EZU
> 
> Also, I can't see that image so I'm not sure how you wired it up to your charge controller.

Thanks. 
Apologies. Here's the connection diagram.
![Untitled Diagram drawio](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/20cd6292-bc72-4dd8-9b1b-628af17dd640)

**Comment by magorm** [comment]
> The CH340G won't work, it only does +/-5V where RS232 needs +/-13V.
> 
> You'll need to use a usb to RS232 converter like this one: https://www.amazon.ca/StarTech-com-USB-Serial-Adapter-Prolific/dp/B00GRP8EZU
> 
> Also, I can't see that image so I'm not sure how you wired it up to your charge controller.

If I use Raspberry Pi, is the Pi serial using +-13v? Thanks in advance.

**Comment by cole8888** [comment]
The Pi is not using that voltage. In my demo it has to go through a breakout board with a MAX3232 on it which handles the voltage boost to talk to the charge controller.

**Comment by cole8888** [comment]
You can see it here:
https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/blob/main/RaspberryPi-Examples/RaspberryPi-Overview.jpg

**Comment by magorm** [comment]
> MAX3232

Thanks. Will try this board, see if it will work - https://shopee.ph/MAX3232-RS232-to-TTL-Serial-Port-Converter-Module-DB9-Connector-MAX232-For-Arduino-i.226548939.4317808086

**Comment by cole8888** [comment]
@magorm Did you get it to work?

**Comment by magorm** [comment]
Not yet. I already setup the raspberry pi zero 2w, made the code run but I think I bought a wrong RS232 adapter. I already ordered the board (https://www.digikey.ph/en/products/detail/mikroelektronika/MIKROE-602/4495610) similar to what you used. Hopefully I can make it work.

Question: from RS232 adapter going to RJ12 (charge controller), I only have to use tx, rx and gnd connection, right?

**Comment by magorm** [comment]
![IMG_1261](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/8e73c7a4-409b-436d-a221-b05141660204)

**Comment by cole8888** [comment]
Yes, you only need rx, tx, and gnd coming from the charge controller.

I've never had much luck getting the dupont cables to make good contact with the DB9 port, so make sure you have good a good connection there.

You can also try swapping around the positions of the yellow and green wires connected to the Pi and the DB9 connector.

**Comment by magorm** [comment]
Hi. How did you get the register address? In the code its 256, not sure if it the same with SRNE charge controller?

**Comment by cole8888** [comment]
I'm using SRNE charge controllers, which ones are you using?

I got it from the SRNE modbus datasheet

**Comment by magorm** [comment]
> I'm using SRNE charge controllers, which ones are you using?
> 
> I got it from the SRNE modbus datasheet

Thanks. I am using the same SCC, specifically ML2440 model.

**Comment by cole8888** [comment]
I have that one also, so you definitely should be able to get it to work with it :)

**Comment by magorm** [comment]
> I have that one also, so you definitely should be able to get it to work with it :)

In rj12, did you use pin1 (tx), pin2 (rx) and pin3(gnd)? pin4 is also gnd but not sure if I should use it instead of pin3?

**Comment by cole8888** [comment]
It should work either way. I only used pin 3 for ground.

**Comment by magorm** [comment]
Hi @cole8888 , for RJ12, the pin 1 is from the left side, right?

![IMG_1267](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/1d497ac0-f036-4668-800f-50809f4fb024)

**Comment by magorm** [comment]
This is the log when I run the script; it is sending  0xff 0x3 0x1 0x0 0x0 0x23 0x10 0x31?
Connection : True
DEBUG:pymodbus.logging:Current transaction state - IDLE
DEBUG:pymodbus.logging:Running transaction 1
DEBUG:pymodbus.logging:SEND: 0xff 0x3 0x1 0x0 0x0 0x23 0x10 0x31
DEBUG:pymodbus.logging:New Transaction state "SENDING"
WARNING:pymodbus.logging:Cleanup recv buffer before send: 0x0 0x0 0x0
DEBUG:pymodbus.logging:Changing transaction state from "SENDING" to "WAITING FOR REPLY"
DEBUG:pymodbus.logging:Changing transaction state from "WAITING FOR REPLY" to "PROCESSING REPLY"
DEBUG:pymodbus.logging:RECV: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
DEBUG:pymodbus.logging:Processing: 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0
DEBUG:pymodbus.logging:Getting transaction 255
DEBUG:pymodbus.logging:Changing transaction state from "PROCESSING REPLY" to "TRANSACTION_COMPLETE"
Failed to read data, reconnecting... 'ModbusIOException' object has no attribute 'registers'

**Comment by cole8888** [comment]
Yes, that's pin one and it is the charge controller tx pin. Here is the pinout:
https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/blob/main/Charge-Controller-Connector-Pinout.png

Can you replace the line containing `read_holding_registers` with response = `modbus.read_holding_registers(256, 35, unit=1, slave=255)`.

This will eliminate any address issues.

Can you follow the steps in this guide to make sure the serial port is enabled in raspi-config: https://pimylifeup.com/raspberry-pi-serial/

Also, can you send a picture of how you've got everything wired everything up now?

**Comment by magorm** [comment]
For the DB9, its 2(rx), 3(tx) and 5(gnd)?

**Comment by cole8888** [comment]
Black (controller rx) goes to pin 2, White (controller tx) goes to pin 3, red (controller gnd) goes to pin 5.

Remember that the pin numbers reverse when comparing the male/female connectors:
![url(1)](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/32819560/5810c478-1db0-4f9f-9132-2acfed0c59b5)

**Comment by magorm** [comment]
Here's my connection. Not sure if the problem is the RJ12? BTW, I am using pymodbus v3.5.4

![Untitled Diagram drawio (1)](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/bf424242-3781-42e6-bf53-a07e90c5d5a9)

**Comment by magorm** [comment]
Yellow - Tx,  Green - Rx,  Black - Gnd,  Red  - Vcc

![pi2](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/7c1833d4-cf36-4d97-9e75-32c5a068f330)
![pi](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/f56f1ab4-e0a0-4d59-a152-0132a6c0699a)

**Comment by magorm** [comment]
<img width="1576" alt="Screenshot 2023-12-12 at 12 23 29 AM" src="https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/daed7dd6-8700-45c8-8db3-81b025a8409a">

**Comment by magorm** [comment]
slave=255
<img width="1576" alt="Screenshot 2023-12-12 at 12 25 03 AM" src="https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/43041cb5-cfef-4c04-ad6b-52e1b8712a44">

**Comment by magorm** [comment]
Serial Enablement: I am using /dev/ttyS0

<img width="1576" alt="Screenshot 2023-12-12 at 12 27 54 AM" src="https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/d6bec19d-4d11-4d9d-91cc-cd368b7d4068">

**Comment by cole8888** [comment]
It looks like your RX and TX are flipped compared to my photo.
Try doing this:
![image](https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/32819560/e1a8b9dc-b46c-4aa5-865b-9fca198fa549)

**Comment by magorm** [comment]
I was able to make it work! Thanks so much @cole8888 ! You are right the problem is wrong connection.

<img width="1131" alt="Screenshot 2023-12-12 at 5 12 53 PM" src="https://github.com/cole8888/SRNE-Solar-Charge-Controller-Monitor/assets/2121324/ca933dae-aff4-4ea7-9372-4368fe550e55">
